version: "3.8"

######################################### Global Environment Variables
x-global-variables: &global-variables
  {
    ENVIRONMENT, APP_NAME, APP_URL, SPA_BACKEND_URL, SPA_FRONTEND_URL, APP_DEBUG,
    START_USER_EMAIL, START_USER_PASSWORD, KIT_AUTH_PASSWORD_GRANT_CLIENT_ID, KIT_AUTH_PASSWORD_GRANT_CLIENT_SECRET,
    CACHE_DRIVER, QUEUE_DRIVER, SESSION_DRIVER, SESSION_LIFE_TIME,
    MYSQL_HOST, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD,
    REDIS_HOST, REDIS_PORT, REDIS_PASSWORD,
    SMTP_USER_NAME, SMTP_USER_PASSWORD, SMTP_EMAIL_FROM,
    PHP_MEMORY_LIMIT, PHP_POST_MAX_SIZE, PHP_UPLOAD_MAX_SIZE, FPM_HOST,
    TRUSTED_PROXY_IP, FCM_SERVER_KEY,
    NGINX_IMAGE_INTERACTS_S3_PROXY_PASS,
    FILESYSTEM_DRIVER, AWS_DEFAULT_REGION, AWS_BUCKET,
    AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY,
    GOOGLE_SERVICES_KEY
  }

######################################### Networks and global extensions
x-project-volumes: &project-volumes
    - /data/fileserver/${PROJECT_NAME_PREFIX}/resources:/var/www/project/storage/app/public
    - /data/fileserver/${PROJECT_NAME_PREFIX}/oauth-keys:/var/www/project/storage/oauth-keys

x-base-env: &base-env
  env_file:
    - ../.env

x-replicated: &replicated-service
  <<: *base-env
  logging:
    driver: json-file
    options:
      max-size: "20m"
      max-file: "4"
  deploy:
    replicas: ${REPLICAS_COUNT}
    mode: replicated
    endpoint_mode: dnsrr
    update_config:
      parallelism: 1
      delay: 7s
    restart_policy:
      condition: on-failure
      delay: 5s
      max_attempts: 3
      window: 120s

networks:
  default:
    external:
      name: ${NETWORK_NAME}

##############################################################################
#                           SERVICES                                         #
##############################################################################

services:
######################################### Required Services
  php:
    <<: *replicated-service
    image: ${HUB_REPOSITORY_DOMAIN}${COMPOSE_PROJECT_NAME}-php:${BUILD_NUMBER:-latest}
    environment: *global-variables
    volumes: *project-volumes

  web:
    <<: *replicated-service
    image: ${HUB_REPOSITORY_DOMAIN}${COMPOSE_PROJECT_NAME}-web:${BUILD_NUMBER:-latest}
    environment:
      <<: *global-variables
      VIRTUAL_HOST: ${APP_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${APP_HOST}
      LETSENCRYPT_EMAIL: shtalinberg@attractgroup.com
      TASK_SLOT: "{{.Task.Slot}}"
      PHP_SERVICE_NAME: "${COMPOSE_PROJECT_NAME}_php"
    volumes: *project-volumes

  migrator:
    image: ${HUB_REPOSITORY_DOMAIN}${COMPOSE_PROJECT_NAME}-php:${BUILD_NUMBER:-latest}
    command: bash -c "composer dump-autoload --optimize && php artisan migrate --seed"
    environment: *global-variables
    networks:
      default: { aliases: [ "${COMPOSE_PROJECT_NAME}.migrator" ] }
    volumes: *project-volumes
    depends_on:
      - db
      - redis
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "4"
    deploy:
      mode: global
      restart_policy:
        condition: none

