version: "3.4"

######################################### Global Environment Variables

x-build: &build-variables
  ENVIRONMENT: ${ENVIRONMENT}
  PACKAGIST_TOKEN: ${PACKAGIST_TOKEN}
  DOCKER_ENV_TYPE: ${DOCKER_ENV_TYPE}
  PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
  PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
  PHP_UPLOAD_MAX_SIZE: ${PHP_UPLOAD_MAX_SIZE}
  PHP_DATE_TIMEZONE: $PHP_DATE_TIMEZONE
  PHP_SMTP: $PHP_SMTP
  PHP_SMTP_PORT: $PHP_SMTP_PORT

##############################################################################
#                           SERVICES                                         #
##############################################################################

services:
######################################### Required Services

  web:
    build:
      context: ../../..
      dockerfile: ./docker/${DOCKER_ENV_TYPE}/nginx/Dockerfile
      args: *build-variables
    image: ${HUB_REPOSITORY_DOMAIN}${COMPOSE_PROJECT_NAME}-web:${BUILD_NUMBER:-latest}

  php:
    build:
      context: ../../..
      dockerfile: ./docker/${DOCKER_ENV_TYPE}/php/Dockerfile
      args: *build-variables
    image: ${HUB_REPOSITORY_DOMAIN}${COMPOSE_PROJECT_NAME}-php:${BUILD_NUMBER:-latest}